# Generated by Django 4.0.4 on 2022-05-04 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('address', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('collection_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('product_description', models.TextField()),
                ('product_url', models.URLField()),
                ('collection', models.CharField(choices=[('PandaZ', 'PandaZ'), ('FoxZ', 'FoxZ'), ('MonkeyZ', 'MonkeyZ')], max_length=20)),
                ('owner', models.CharField(choices=[('Hamza', 'Hamza')], max_length=20)),
            ],
        ),
    ]
