# Generated by Django 4.0.4 on 2022-05-04 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0002_product_product_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_img',
            new_name='img_url',
        ),
    ]
