# Generated by Django 4.0.2 on 2022-05-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0003_rename_product_img_product_img_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='user_name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='account',
            name='password',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='owner',
            field=models.CharField(choices=[('Hamza', 'Hamza'), ('Aymen', 'Aymen')], max_length=20),
        ),
    ]
