# Generated by Django 4.0.2 on 2022-05-07 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0005_register_delete_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='confpass',
        ),
    ]
