# Generated by Django 4.0.2 on 2022-05-15 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0006_remove_register_confpass'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='Account',
        ),
    ]
