# Generated by Django 4.0.2 on 2022-05-22 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0007_rename_register_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='password',
            new_name='password1',
        ),
        migrations.AddField(
            model_name='account',
            name='password2',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
    ]
