# Generated by Django 4.0.2 on 2022-05-23 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0009_rename_address_account_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='email',
            new_name='address',
        ),
    ]
