# Generated by Django 4.0.2 on 2022-05-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0011_rename_password1_account_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='collection_url',
        ),
        migrations.AddField(
            model_name='collection',
            name='description',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collection',
            name='photo',
            field=models.ImageField(default=3, upload_to='nft'),
            preserve_default=False,
        ),
    ]
